// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: xhzzgekbgydbcgmrodti

class SupabaseConfig {
  static const String supabaseUrl = 'https://xhzzgekbgydbcgmrodti.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoenpnZWtiZ3lkYmNnbXJvZHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjY1NjEsImV4cCI6MjA3Nzk0MjU2MX0.UEjNugvL7Z3a2To-Dosb9RNlJaUS-KIt0WWiCspOZbI';
}
